TRADE = "TradeName"
DATE = "Date"
START = "Start_PV"
END = "End_PV"
TOTAL = "Total_PnL"
EXPLAINED = "Explained"
UNEXPLAINED = "Residual"
TOTAL_JUMP = "TotalJump"
UNEXPLAINED_JUMP = "ResidualJump"
PNL_SLICES = [
    "Basis_CoF_PnL", "Recovery_Rate_PnL", "Rates_PnL", "Model_PnL", "Basis_CoT_PnL", "Credit_Index_PnL", "Credit_Single_PnL"
]
QC_AGG = "QC_Aggregated"
QC_FLAG = "QC_Flag"
IF_SCORE = "IF_score"
ROBUST_Z_SCORE = "RobustZ_score"
ROLLING_SCORE = "Rolling_score"
IQR_SCORE = "IQR_score"
AGGREGATED_SCORE = "QC_Aggregated"
SCORE_FLAG = "QC_Flag"
DEFAULT_SCORES = [IF_SCORE, ROBUST_Z_SCORE, ROLLING_SCORE, IQR_SCORE, AGGREGATED_SCORE, SCORE_FLAG]